version: "3.7"

services:
  database:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data

    env_file:
      - ./.env
    ports:
      - "5432:5432"
  #  frontend:

  backend:
    build: ./backend/triangle # путь до докерфайла
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - database
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  frontend:
    restart: always
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/frontend:/code
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run start"]

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_volume:
  static_volume:
  media_volume:
